# Generated by Django 3.2.12 on 2022-04-09 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(choices=[('Vanzari', 'Vanzari'), ('Cumparari', 'Cumparari'), ('Balanta', 'Balanta')], max_length=30, verbose_name='Type: ')),
                ('date', models.DateField(verbose_name='Date: ')),
                ('time', models.TimeField(verbose_name='Time: ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price: ')),
                ('message', models.TextField(verbose_name='Message: ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
